#!/bin/sh

##
##
## Author: Nir Geier nir.geier@gmail.com
##
##

# Check to see if this is the first commit in the repository or not
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    # We compare our changes against the prevoius commit
	against=HEAD^
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to screen.
exec 1>&2

# Check to see if we have updated the bower.json file
#if [ $(git diff-tree -r --name-only $against | grep * ) ];
#then

    # Output colors
	red='\033[0;31m';
	green='\033[0;32m';
	yellow='\033[0;33m';
	default='\033[0;m';
	
	# personal touch :-)
	echo "${red}"
	echo "                                         "
	echo "                   |ZZzzz                "
	echo "                   |                     "
	echo "                   |                     "
	echo "      |ZZzzz      /^\            |ZZzzz  "
	echo "      |          |~~~|           |       "
	echo "      |        |-     -|        / \      "
	echo "     /^\       |[]+    |       |^^^|     "
	echo "  |^^^^^^^|    |    +[]|       |   |     "
	echo "  |    +[]|/\/\/\/\^/\/\/\/\/|^^^^^^^|   "
	echo "  |+[]+   |~~~~~~~~~~~~~~~~~~|    +[]|   "
	echo "  |       |  []   /^\   []   |+[]+   |   "
	echo "  |   +[]+|  []  || ||  []   |   +[]+|   "
	echo "  |[]+    |      || ||       |[]+    |   "
	echo "  |_______|------------------|_______|   "
	echo "                                         "
	echo "                                         "
	echo "      ${green}You have just commited code ${red}   " 
	echo "         Your code ${yellow}is bad.!!!  ${red} Do not ever commit again       "
	echo "                                         "
	echo "${no_color}"
#fi;

exit 0;
